---
kind: pipeline
name: amd64
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: rancher/dapper:v0.5.6
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: cache package
    image: curlimages/curl:7.77.0
    environment:
      PASSWORD:
        from_secret: drone_upload_password
      USERNAME:
        from_secret: drone_upload_username
    commands:
      - "tar -czvf /tmp/$DRONE_COMMIT.tar.gz ./dist/artifacts/k3os-amd64.iso ./dist/artifacts/k3os-initrd-amd64 ./dist/artifacts/k3os-kernel-amd64.squashfs ./dist/artifacts/k3os-kernel-version-amd64 ./dist/artifacts/k3os-rootfs-amd64.tar.gz ./dist/artifacts/k3os-vm-amd64.iso ./dist/artifacts/update-vm-amd64.run ./dist/artifacts/update-vm-amd64.run"
      - "curl -u $USERNAME:$PASSWORD -F file=@/tmp/$DRONE_COMMIT.tar.gz https://upload.bohicalabs.com"
    when:
      branch:
        exclude:
          - master
      repo:
        - BOHICA-LABS/BLAOS

  - name: create releaselog
    image: quay.io/git-chglog/git-chglog:latest
    commands:
      - "git fetch origin --prune --tags"
      - "git-chglog ${DRONE_TAG} > RELEASELOG.md"
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: global_github_token
      files:
        - "dist/artifacts/*"
        - RELEASELOG.md
      note: RELEASELOG.md
      title: "Release ${DRONE_TAG}"
      overwrite: true
      checksum:
        - sha256
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "bohicalabs/blaos"
      tag: "${DRONE_TAG}-amd64"
      username:
        from_secret: docker_username
    when:
      repo:
        - BOHICA-LABS/BLAOS
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: changelog
type: docker

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: clone
    image: plugins/git-action:1
    settings:
      actions:
        - clone
      remote: ${DRONE_GIT_HTTP_URL}
      branch: master
      path: /drone/src
      netrc_machine: github.com
      netrc_username:
        form_secret: global_github_username
      netrc_password:
        form_secret: global_github_token

  - name: generate
    image: quay.io/git-chglog/git-chglog:latest
    commands:
      - "git fetch origin --prune --tags"
      - "git-chglog > CHANGELOG.md"

  - name: diff
    image: alpine/git:latest
    commands:
      - "git diff"

  - name: output
    image: alpine:latest
    commands:
      - "cat CHANGELOG.md"

  - name: publish
    image: plugins/git-action:1
    settings:
      actions:
        - commit
        - push
      message: "docs(changelog): auto changelog update ${DRONE_TAG} [CI SKIP]"
      author_email: devops@bohicalabs.com
      author_name: bohicalabs
      branch: master
      path: /drone/src
      netrc_machine: github.com
      netrc_username:
        from_secret: global_github_username
      netrc_password:
        from_secret: global_github_token

trigger:
  event:
    - tag
  ref:
    - refs/heads/master
    - refs/tags/*

---
kind: pipeline
name: mirroring
type: docker

clone:
  disable: true

steps:
  - name: mirror
    image: bohicalabs/drone-git-mirror:1.0.7
    settings:
      target_repo: github.com/1898andCo/HAOS.git
      git_domain: github.com
      git_username:
        from_secret: global_github_username
      git_password:
        from_secret: global_github_token

trigger:
  ref:
    - refs/head/master
    - refs/tags/*
  repo:
    - BOHICA-LABS/BLAOS