---
kind: pipeline
name: amd64
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: rancher/dapper:v0.5.6
    commands:
      - dapper test
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: build
    image: rancher/dapper:v0.5.6
    commands:
      - dapper build
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: validate
    image: rancher/dapper:v0.5.6
    commands:
      - dapper validate
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: package
    image: rancher/dapper:v0.5.6
    commands:
      - dapper package
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: create releaselog
    image: quay.io/git-chglog/git-chglog:latest
    commands:
      - "git fetch origin --prune --tags"
      - "git-chglog ${DRONE_TAG} > RELEASELOG.md"
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: global_github_token
      files:
        - "dist/artifacts/*"
        - RELEASELOG.md
      note: RELEASELOG.md
      title: "Release ${DRONE_TAG}"
      overwrite: true
      checksum:
        - sha512
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: changelog
type: docker

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: clone
    image: plugins/git-action:1
    settings:
      actions:
        - clone
      remote: ${DRONE_GIT_HTTP_URL}
      branch: master
      path: /drone/src
      netrc_machine: github.com
      netrc_username:
        form_secret: global_github_username
      netrc_password:
        form_secret: global_github_token

  - name: generate
    image: quay.io/git-chglog/git-chglog:latest
    commands:
      - "git fetch origin --prune --tags"
      - "git-chglog > CHANGELOG.md"

  - name: diff
    image: alpine/git:latest
    commands:
      - "git diff"

  - name: output
    image: alpine:latest
    commands:
      - "cat CHANGELOG.md"

  - name: publish
    image: plugins/git-action:1
    settings:
      actions:
        - commit
        - push
      message: "docs(changelog): auto changelog update ${DRONE_TAG} [CI SKIP]"
      author_email: devops@bohicalabs.com
      author_name: bohicalabs
      branch: master
      path: /drone/src
      netrc_machine: github.com
      netrc_username:
        from_secret: global_github_username
      netrc_password:
        from_secret: global_github_token

trigger:
  event:
    - tag
  ref:
    - refs/heads/master
    - refs/tags/*

---
kind: pipeline
name: syncrepo
type: docker

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: clone main develop
    image: plugins/git-action:1
    settings:
      actions:
        - clone
      remote: ${DRONE_GIT_HTTP_URL}
      branch: develop
      path: /drone/src/source/develop
      netrc_machine: github.com
      netrc_username:
        form_secret: global_github_username
      netrc_password:
        form_secret: global_github_token
    when:
      ref:
        - refs/heads/develop

  - name: clone remote develop
    image: plugins/git-action:1
    settings:
      actions:
        - clone
      remote: https://github.com/1898-Co/HAOS.git
      branch: develop
      path: /drone/src/remote/develop
      netrc_machine: github.com
      netrc_username:
        form_secret: global_github_username
      netrc_password:
        form_secret: global_github_token
    when:
      ref:
        - refs/heads/develop

  - name: Overwrite
    image: alpine:latest
    commands:
      - "rm -rf /drone/src/remote/develop/*"
      - "cp /drone/src/source/develop /drone/src/remote/develop/"
    when:
      ref:
        - refs/heads/develop

  - name: publish remote develop
    image: plugins/git-action:1
    settings:
      actions:
        - commit
        - push
      message: "chore(sync): auto sync develop [CI SKIP]"
      author_email: devops@bohicalabs.com
      author_name: bohicalabs
      branch: develop
      path: /drone/src/remote/develop/
      netrc_machine: github.com
      netrc_username:
        from_secret: global_github_username
      netrc_password:
        from_secret: global_github_token
    when:
      ref:
        - refs/heads/develop

trigger:
  repo:
    - BOHICA-LABS/BLAOS