---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: rancher/dapper:v0.4.2
  commands:
  - dapper test
  volumes:
  - name: docker
    path: /var/run/docker.sock