# See https://github.com/1898andCo/HAOSblob/master/README.md#configuration
# and https://github.com/1898andCo/HAOSblob/master/README.md#remastering-iso
# This file is a placeholder for custom configuration when building a custom ISO image.
