# See https://github.com/BOHICA-LABS/BLAOS/blob/master/README.md#configuration
# and https://github.com/BOHICA-LABS/BLAOS/blob/master/README.md#remastering-iso
# This file is a placeholder for custom configuration when building a custom ISO image.
