#!/bin/bash

setup_ssh()
{
    if [ ! -e /var/lib/rancher/BLAOS/ssh ]; then
        mkdir -p /var/lib/rancher/BLAOS
        cp -rf /etc/ssh /var/lib/rancher/BLAOS/ssh
    fi
    rm -rf /etc/ssh
    ln -s /var/lib/rancher/BLAOS/ssh /etc/ssh
}

setup_rancher_node()
{
    mkdir -p /etc/rancher
    mkdir -p /var/lib/rancher/BLAOS/node
    ln -s /var/lib/rancher/BLAOS/node /etc/rancher/
}

setup_ssh
setup_rancher_node
