#!/bin/bash

TARGET=/run/BLAOS/target

source /usr/lib/os-release

grow()
{
    parted $1 resizepart $2 100%
    partprobe $1
    sleep 2
    e2fsck -f $3
    resize2fs $3
}

setup_mounts()
{
    mkdir -p $TARGET
    mount -L BLAOS_STATE $TARGET

    if [ -e $TARGET/BLAOS/system/growpart ]; then
        read DEV NUM < $TARGET/BLAOS/system/growpart
        if [ ! -e "${DEV}${NUM}" ]; then
            # /dev/sda2 => /dev/sda2
            # /dev/nvme0n1p2 => /dev/nvme0n1p2
            PART=$(blkid -L BLAOS_STATE)

            # /dev/sda2 => /dev/sda
            # /dev/nvme0n1p2 => /dev/nvme0n1
            DEV=$(echo "$PART" | sed -r 's/((\d+)p)?\d+$/\2/')

            # /dev/sda2 => 2
            # /dev/nvme0n1p2 => 2
            NUM=$(echo "$PART" | sed 's!.*[^0-9]!!')
        fi
        if [ -e "${PART:=${DEV}${NUM}}" ]; then
            umount $TARGET
            grow $DEV $NUM $PART || true
            mount -L BLAOS_STATE $TARGET
        fi
        rm -f $TARGET/BLAOS/system/growpart
    fi
}

setup_kernel_squashfs()
{
    KER_SRC="/.base/BLAOS/system/kernel/$(uname -r)/kernel.squashfs"
    KER_DEST="$TARGET/BLAOS/system/kernel/$(uname -r)/kernel.squashfs"
    if [ -e $KER_SRC ] && [ ! -e $KER_DEST ]; then
        mkdir -p $(dirname ${KER_DEST})
        cp -r $KER_SRC $KER_DEST
    fi
}

setup_BLAOS()
{
    if [ -e $TARGET/BLAOS/system/BLAOS/current/BLAOS ]; then
        return 0
    fi

    BLAOS_SRC=/.base/BLAOS/system/BLAOS/current/BLAOS
    BLAOS_FILE=$TARGET/BLAOS/system/BLAOS/${VERSION_ID}/BLAOS

    if [ ! -e ${BLAOS_SRC} ]; then
        return 0
    fi

    if [ ! -e ${BLAOS_FILE} ]; then
        mkdir -p $(dirname ${BLAOS_FILE}.tmp)
        cp -f ${BLAOS_SRC} ${BLAOS_FILE}.tmp
        mv -f ${BLAOS_FILE}.tmp ${BLAOS_FILE}
    fi

    ln -sf ${VERSION_ID} $TARGET/BLAOS/system/BLAOS/current
}

setup_init()
{
    if [ -e $TARGET/sbin/init ]; then
        return 0
    fi

    mkdir -p $TARGET/sbin
    ln -sf ../BLAOS/system/BLAOS/current/BLAOS $TARGET/sbin/init
}

setup_k3s()
{
    if [ -e $TARGET/BLAOS/system/k3s/current/k3s ]; then
        return 0
    fi

    for i in $(ls -drt $TARGET/BLAOS/system/k3s/*); do
        if [ ! -L "$i" ]; then
            LATEST=$i
            break
        fi
    done

    if [ -e "${LATEST}" ]; then
        ln -sf $(basename "${LATEST}") $TARGET/BLAOS/system/k3s/current
        return 0
    fi
}

takeover()
{
    if [ ! -e BLAOS/system/takeover ]; then
        return 0
    fi

    touch BLAOS/system/factory-reset

    if [ -L sbin ]; then
      rm -f sbin
    fi

    for i in *; do
        case $i in
            boot|BLAOS|sbin)
                ;;
            *)
                rm -rf $i
        esac
    done
    for i in sbin/*; do
        case $i in
            sbin/init|sbin/k3s|sbin/BLAOS)
                ;;
            *)
                rm -rf "$i"
        esac
    done

    rm -rf boot/[^g]*
    rm -f BLAOS/system/takeover
    rm -rf BLAOS/data
    sync
    
    if [ -e BLAOS/system/poweroff ]; then
        rm -f BLAOS/system/poweroff
        poweroff -f
    else
        reboot -f
    fi
}

setup_mounts
setup_BLAOS
setup_kernel_squashfs
setup_init
setup_k3s

cd $TARGET

takeover || true

if [ -e BLAOS/system/factory-reset ] || [ -e BLAOS/system/ephemeral ]; then
    rm -rf BLAOS/data BLAOS/system/factory-reset
fi

losetup -d /dev/loop0 || true
mount --make-rprivate /
mkdir -p .root
pivot_root . .root
BLAOS_MODE=local exec /sbin/init
