#!/bin/sh

commit_msg_file=$1

if ! grep -q "^(fix|feature|chore|refactor|deps)" "$commit_msg_file"; then
    echo "Please begin commit message with 'fix','feature','chore','refactor'"
    exit 1
fi

if ! grep -q ":" "$commit_msg_file"; then
    echo "Please divide commit message with ':'"
    exit 1
fi
