#!/bin/bash
set -e

rescue() {
    echo ERROR "Something went wrong, run with cmdline BLAOS.debug for more logging"
    echo Dropping to shell
    exec bash
}

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

. /usr/libexec/BLAOS/functions
. /usr/lib/os-release

pinfo Welcome to $PRETTY_NAME

if [ "$BLAOS_DEBUG" = "true" ]; then
    set -x
fi

if ! ${SCRIPTS}/bootstrap; then
    rescue
fi

exec >/dev/console </dev/console 2>&1

reinit_debug

if ! ${SCRIPTS}/mode; then
    rescue
fi

trap rescue EXIT

export BLAOS_MODE=$(</run/BLAOS/mode)
pinfo Running mode: ${BLAOS_MODE}
source $SCRIPTS/mode-${BLAOS_MODE}

pinfo Booting system
source $SCRIPTS/boot

exec /sbin/init
