#!/bin/bash
set -e

cd $(dirname $0)/..

echo "prepping for haos distribution"
# CP HAOS files

rm -rf $(pwd)/overlay/share/rancher/k3s/server/manifests/system-upgrade-plans/haos-latest.yaml
rm -rf $(pwd)overlay/sbin/update-issue
cp -rf $(pwd)/haos/haos-latest.yaml $(pwd)/overlay/share/rancher/k3s/server/manifests/system-upgrade-plans/haos-latest.yaml
cp -rf $(pwd)/haos/update-issue $(pwd)/overlay/sbin/update-issue
