#!/bin/bash
set -e

source $(dirname $0)/version
source $(dirname $0)/images

cd $(dirname $0)/..
echo "Creating Image Packages"
DIST=$(pwd)/dist/artifacts

pushd images/output
build_all "$@"
mkdir -p ${DIST}
copy_all ${DIST} "$@"
popd

mkdir -p ./build
ID=$(docker create ${REPO}/haos-package:${TAG})
docker cp ${ID}:/output/haos ./build/
docker rm -fv $ID

docker build \
    --build-arg ARCH=${ARCH} \
    --build-arg REPO=${REPO} \
    --build-arg TAG=${TAG} \
    --build-arg VERSION=${VERSION} \
    --file package/Dockerfile \
    --tag ${REPO}/haos:${TAG} \
    --tag ${REPO}/haos:latest \
    .
docker image save --output ./dist/images.tar \
    ${REPO}/haos:${TAG} \
    ${REPO}/haos:latest
echo ${REPO}/haos:${TAG} >./dist/images.txt
echo Built ${REPO}/haos:${TAG}
