#!/bin/sh

set -e
if [ "$(go env GOARCH)" = "arm64" ]; then
    curl -sL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.38.0
fi
curl -sL https://github.com/megastep/makeself/releases/download/release-${MAKEVER}/makeself-${MAKEVER}.run --output makeself-${MAKEVER}.run &&
    chmod 755 makeself-${MAKEVER}.run &&
    ./makeself-${MAKEVER}.run &&
    cd makeself-${MAKEVER} &&
    mv *.sh /usr/bin &&
    makeself.sh --version

cd /go/src/github.com/1898andco/HAOS
sh scripts/ci
