#!/bin/bash

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="$(git describe --always --tags)${DIRTY}"
fi

if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

ARCH=${ARCH:-"amd64"}

K3s_VERSION="$(grep 'ENV VERSION' images/10-k3s/Dockerfile | cut -d ' ' -f3)"
TAG=${TAG:-"${VERSION}-${ARCH}-${K3s_VERSION}"}
REPO=${REPO:-1898andco}
