#!/bin/bash
set -e

export SCRIPTS=/usr/libexec/haos
export HAOS_SYSTEM=/.base/haos/system

reinit_debug()
{
    if [ "$HAOS_DEBUG" = "true" ]; then
        set -x
        return 0
    fi

    if [ -e /run/haos/debug ]; then
        set -x
        return 0
    fi

    if [ -e /proc/cmdline ]; then
        for x in $(cat /proc/cmdline); do
            case $x in
                haos.debug*)
                    export HAOS_DEBUG=true
                    mkdir -p /run/haos
                    echo debug > /run/haos/debug || true
                    ;;
            esac
        done
    fi

    if [ "$HAOS_DEBUG" = "true" ]; then
        set -x
    fi
}

setup_kernel()
{
    KERNEL=${HAOS_SYSTEM}/kernel/$(uname -r)/kernel.squashfs
    if [ ! -e ${KERNEL} ]; then
        return 0
    fi

    mkdir -p /run/haos/kernel
    mount -t squashfs $KERNEL /run/haos/kernel

    mount --bind /run/haos/kernel/lib/modules /lib/modules
    mount --bind /run/haos/kernel/lib/firmware /lib/firmware
    mount --bind /run/haos/kernel/headers /usr/src

    umount /run/haos/kernel
}

perr()
{
    echo "[ERROR]" "$@" 1>&2
}

pfatal()
{
    echo "[FATAL]" "$@" 1>&2
    exit 1
}

pinfo()
{
    echo " * " "$@"
}

cleanup()
{
    rm -rf /run/haos
    unset SCRIPTS
    unset HAOS_SYSTEM
    if [ -n "$HAOS_MODE" ]; then
        mkdir -p /run/haos
        echo "$HAOS_MODE" > /run/haos/mode
    fi
    unset HAOS_MODE
}

reinit_debug
