#!/bin/bash

setup_motd() {
    echo >>/etc/motd
    echo 'You can configure this system or install to disk using "sudo haos install"' >>/etc/motd
}

setup_base() {
    HAOS_ISO=$(blkid -L HAOS || true)
    if [ -n "$HAOS_ISO" ]; then
        mount -o ro $(blkid -L HAOS) /.base
    else
        success=false
        for ((j = 0; j < 5; j++)); do
            for i in $(lsblk -o NAME,TYPE -n | grep -w disk | awk '{print $1}'); do
                if mount /dev/$i /.base; then
                    success=true
                    break
                fi
            done
            if [ "$success" = "true" ]; then
                break
            else
                pinfo "Waiting for USB for $((j + 1)) seconds"
                sleep 1
            fi
        done
    fi
}

setup_passwd() {
    # no passwords in live mode
    passwd -d 1898andco >/dev/null 2>&1
}

setup_base
setup_kernel
setup_passwd
setup_motd
