# Responsible for generating changelog
# TODO: this is not grouping things properly.
# NOTE: uses the file `changelog-ci-config.json` in the root of the repo
name: Changelog 

on: 
  pull_request:
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Changelog 
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          config_file: changelog-ci-config.json