name: Parse Comments for Actions
on:
    push:
    workflow_dispatch:

permissions:

jobs:
  todo:              
    runs-on: ubuntu-latest  
    steps:
        - name: Harden the runner (Audit all outbound calls)
          uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
          with:
            egress-policy: audit

        - name: TODO to Issue
          uses: alstr/todo-to-issue-action@5c97b3cb39d2d868453245e62bccc9a022b6d680 # v4.11.1