# Responsible for linting the codebase. Comments will be 
# added to the PR if any linting errors are found.
name: Golang Linting
on: [push]

permissions:
  contents: read

jobs:
  golangci:
    name: Go Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go 
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'
          cache: false
      - name: Install golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        
