# Responsible for packaging and releasing the application
name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master  # release
      - develop # release candidate
      - workflow-test # for testing

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Release
        run: make  
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        env:
#            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#        with:
#            files: ./dist/*
#            tag_name: ${{ github.ref }}
#            body: Release ${{ github.ref }} ${{ github.event.head_commit.message }}
#            draft: ${{ github.ref == 'refs/heads/develop'}}
