# Responsible for validating the CODEOWNERS file
name: Validate Codeowners
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  validate-codeowners:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout source code at current commit"
      uses: actions/checkout@v3
      # Leave pinned at 0.7.1 until https://github.com/mszostok/codeowners-validator/issues/173 is resolved
    - uses: mszostok/codeowners-validator@v0.7.1
      name: "Full check of CODEOWNERS"
      with:
        checks: "syntax,files,duppatterns"
        github_access_token: "${{ github.token }}"
